release = "19.12"
environment = "UNKNOWN"

[fail]
enabled = false
after = 3

[metrics]
enabled = true

[apis]

 [apis.image]
 url = "http://iotd/image"

 [apis.access]
 url = "http://accesslog/access-log"
