name: Release tagged version

on:
  push:
    tags:
      - 'v*'

jobs:

  trigger-app-version-update:  
    runs-on: ubuntu-latest
    steps:

    - name: Set image tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Dispatch version update workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Update version tags
        inputs: '{"tag":"v0.4"}'
        repo: sixeyed/apod-app        
        token: ${{ secrets.ACCESS_TOKEN }}